import { Route, Routes, Link } from "react-router-dom";
import Header from "../components/header";
import Footer from "../components/footer";
import ProductPage from "./client/productPage";
import ProductOverview from "./client/productOverview";
import CartPage from "./client/cartPage";
import CheckoutPage from "./client/checkoutPage";
import ProfilePage from "./client/profilePage";
import ProductReviewsPage from "./client/productReviewsPage";
import { Sparkles, Truck, ShieldCheck, Leaf, Mail, Phone, MapPin, Clock, MessageCircle } from "lucide-react";

function LandingPage(){return <div className="w-full"><section className="relative w-full min-h-[70vh] sm:min-h-[85vh] flex items-center justify-center bg-[url('/bg4.jpg')] bg-cover bg-center"><div className="absolute inset-0 bg-gradient-to-b from-black/50 via-black/30 to-black/60"/><div className="relative z-10 text-center px-6 max-w-3xl animate-fade-in-up"><span className="inline-flex items-center gap-2 text-accent bg-white/10 backdrop-blur-sm border border-white/20 px-4 py-1.5 rounded-full text-xs sm:text-sm font-semibold mb-6"><Sparkles size={14}/> NEW SEASON COLLECTION</span><h1 className="font-display text-4xl sm:text-6xl font-bold text-white mb-5 leading-tight">Radiant Skin, <br className="hidden sm:block"/>Naturally Yours</h1><p className="text-white/80 text-base sm:text-lg mb-8 max-w-xl mx-auto">Discover Crystal Beauty Clear's curated range of skincare and cosmetics, selected to help bring out your natural glow.</p><Link to="/products" className="inline-block bg-accent hover:bg-accent-dark text-white font-semibold px-8 py-3.5 rounded-full shadow-lg">Shop the Collection</Link></div></section><section className="max-w-7xl mx-auto px-6 sm:px-8 py-14 grid grid-cols-1 sm:grid-cols-3 gap-6">{[{icon:Leaf,title:'Carefully Selected',desc:'Quality-focused skincare and beauty products for everyday routines.'},{icon:Truck,title:'Island-wide Delivery',desc:'Convenient delivery with clear order updates from checkout to arrival.'},{icon:ShieldCheck,title:'Customer Support',desc:'Friendly assistance for product questions, orders and after-sales help.'}].map(({icon:Icon,title,desc})=><div key={title} className="bg-secondary/60 rounded-2xl p-6 flex items-start gap-4"><div className="w-11 h-11 shrink-0 rounded-xl bg-accent/15 flex items-center justify-center text-accent-dark"><Icon size={22}/></div><div><h3 className="font-semibold mb-1">{title}</h3><p className="text-sm text-ink-soft leading-relaxed">{desc}</p></div></div>)}</section><section className="max-w-7xl mx-auto px-4 sm:px-8 pb-16"><div className="flex items-center justify-between mb-6 px-2"><h2 className="font-display text-2xl sm:text-3xl font-bold">Best Sellers</h2><Link to="/products" className="text-accent-dark text-sm font-semibold">View all →</Link></div><ProductPage limit={8} hideHeading/></section></div>}
function About(){return <section className="max-w-6xl mx-auto px-6 py-14 sm:py-20"><div className="text-center max-w-3xl mx-auto mb-12"><span className="text-accent-dark text-sm font-bold tracking-[0.2em] uppercase">About Crystal Beauty Clear</span><h1 className="font-display text-4xl sm:text-5xl font-bold mt-3 mb-5">Beauty care made simple, thoughtful and accessible.</h1><p className="text-ink-soft leading-8">Crystal Beauty Clear brings together skincare and cosmetic products selected around practical routines, quality, value and customer care. Our goal is to make it easier to discover products you can understand, order confidently and enjoy as part of your everyday self-care.</p></div><div className="grid md:grid-cols-3 gap-5">{[['Our Approach','We focus on clear product information, honest pricing and a smooth shopping experience from browsing to delivery.'],['Product Selection','Our collection is organized to help customers compare options, discover new essentials and choose products that fit their routines.'],['Customer First','Questions about a product or order? Our support channels are available to help before and after purchase.']].map(([t,d])=><article key={t} className="bg-white rounded-2xl border border-accent/15 p-7 shadow-sm"><h2 className="font-display text-xl font-bold mb-3">{t}</h2><p className="text-ink-soft leading-7">{d}</p></article>)}</div></section>}
function Contact(){return <section className="max-w-6xl mx-auto px-6 py-14 sm:py-20"><div className="text-center max-w-3xl mx-auto mb-12"><span className="text-accent-dark text-sm font-bold tracking-[0.2em] uppercase">We're here to help</span><h1 className="font-display text-4xl sm:text-5xl font-bold mt-3 mb-4">Contact Crystal Beauty Clear</h1><p className="text-ink-soft leading-7">Reach out for product information, order assistance, delivery questions or general enquiries. We aim to respond as soon as possible during business hours.</p></div><div className="grid lg:grid-cols-2 gap-6"><div className="bg-secondary/60 rounded-2xl p-7 space-y-6"><h2 className="font-display text-2xl font-bold">Contact details</h2>{[[Mail,'Email','hello@crystalbeautyclear.com'],[Phone,'Phone','+94 11 234 5678'],[MessageCircle,'WhatsApp','+94 77 234 5678'],[MapPin,'Location','Colombo, Sri Lanka'],[Clock,'Business hours','Monday – Saturday · 9:00 AM – 6:00 PM']].map(([I,t,v])=><div key={t} className="flex gap-4"><div className="w-10 h-10 rounded-xl bg-accent/15 text-accent-dark flex items-center justify-center shrink-0"><I size={19}/></div><div><p className="font-semibold">{t}</p><p className="text-sm text-ink-soft mt-1">{v}</p></div></div>)}</div><div className="bg-white rounded-2xl border border-accent/15 p-7 shadow-sm"><h2 className="font-display text-2xl font-bold mb-3">Before you contact us</h2><p className="text-ink-soft leading-7 mb-5">For an existing order, please include your order number (for example, CBC00001) so our team can locate it quickly. For product questions, include the product name or product ID.</p><div className="space-y-3 text-sm text-ink-soft"><p>• Order and delivery support</p><p>• Product availability and details</p><p>• Returns and general enquiries</p><p>• Website and account assistance</p></div><a href="mailto:hello@crystalbeautyclear.com" className="inline-flex mt-7 bg-accent hover:bg-accent-dark text-white px-6 py-3 rounded-xl font-semibold">Email us</a></div></div></section>}
export default function HomePage(){return <div className="w-full min-h-screen flex flex-col bg-primary"><Header/><div className="w-full flex-1"><Routes><Route path="/" element={<LandingPage/>}/><Route path="/products" element={<div className="max-w-7xl mx-auto w-full px-4 sm:px-8 py-8"><ProductPage/></div>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/overview/:id" element={<ProductOverview/>}/><Route path="/reviews/:id" element={<ProductReviewsPage/>}/><Route path="/cart" element={<CartPage/>}/><Route path="/checkout" element={<CheckoutPage/>}/><Route path="/profile" element={<ProfilePage/>}/><Route path="*" element={<div className="py-24 text-center"><h1 className="text-2xl font-bold">404 - Page Not Found</h1></div>}/></Routes></div><Footer/></div>}
