import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import api, { getErrorMessage } from "../../utils/api";
import { getUser, saveSession } from "../../utils/auth";
import { Package, UserRound } from "lucide-react";

export default function ProfilePage(){
  const [user,setUser]=useState(getUser()); const [orders,setOrders]=useState([]); const [form,setForm]=useState({firstName:user?.firstName||'',lastName:user?.lastName||'',img:user?.img||''}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  useEffect(()=>{Promise.all([api.get('/api/users/me'),api.get('/api/orders/mine')]).then(([u,o])=>{setUser(u.data.user);setForm({firstName:u.data.user.firstName,lastName:u.data.user.lastName,img:u.data.user.img||''});setOrders(o.data.orders||[]);saveSession({user:u.data.user});}).catch(err=>toast.error(getErrorMessage(err,'Could not load your profile'))).finally(()=>setLoading(false))},[]);
  const save=async(e)=>{e.preventDefault();setSaving(true);try{const r=await api.put('/api/users/me',form);setUser(r.data.user);saveSession({user:r.data.user});toast.success('Profile updated');}catch(err){toast.error(getErrorMessage(err,'Could not update profile'));}finally{setSaving(false)}};
  return <div className="max-w-6xl mx-auto px-4 sm:px-8 py-10"><h1 className="font-display text-3xl sm:text-4xl font-bold mb-8">My Profile</h1><div className="grid lg:grid-cols-[380px_1fr] gap-6"><form onSubmit={save} className="bg-white rounded-2xl border border-accent/15 p-6 h-fit"><div className="flex items-center gap-3 mb-6"><div className="w-12 h-12 rounded-full bg-accent/15 flex items-center justify-center text-accent-dark"><UserRound/></div><div><h2 className="font-bold">{user?.email}</h2><p className="text-sm text-ink-soft">Customer account</p></div></div>{[['firstName','First name'],['lastName','Last name'],['img','Profile image URL']].map(([k,l])=><label key={k} className="block text-sm font-semibold mb-4">{l}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-2 w-full rounded-xl border border-accent/25 px-4 py-3" /></label>)}<button disabled={saving} className="w-full bg-accent text-white py-3 rounded-xl font-semibold">{saving?'Saving...':'Save Changes'}</button></form><section className="bg-secondary/50 rounded-2xl p-6"><div className="flex items-center justify-between mb-5"><h2 className="font-display text-2xl font-bold">My Orders</h2><Package className="text-accent-dark"/></div>{loading?<p className="text-ink-soft">Loading...</p>:orders.length===0?<p className="text-ink-soft">You have not placed any orders yet. <Link to="/products" className="text-accent-dark font-semibold">Shop now</Link></p>:<div className="space-y-3">{orders.map(o=><div key={o._id} className="bg-white rounded-xl p-4 border border-accent/10 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><p className="font-mono text-sm font-semibold">{o.orderId}</p><p className="text-xs text-ink-soft">{o.date?new Date(o.date).toLocaleString():''} · {o.products?.reduce((s,p)=>s+p.quantity,0)||0} item(s)</p></div><div className="flex items-center gap-4"><span className="capitalize text-sm font-semibold">{o.status}</span><span className="font-bold">LKR {Number(o.total||0).toFixed(2)}</span></div></div>)}</div>}</section></div></div>;
}
